#server:
#  port: 8080
#
#spring:
#  datasource:
#    name: borrowmybook
#    url: jdbc:postgresql://dpg-ceh1oota499apbk7f290-a.oregon-postgres.render.com/borrowmybook
#    # TODO: It's not secure to leave credentials in code, need to move to github secrets/vault
#    username: borrowmybook_user
#    password: jCcqAg2fpwAy9QaQf4ica78L9gntJHOc
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect:  org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      # TODO: using "ddl-auto: none" is good practice. We will use Liquibase/FlyWay for db migration and versioning on UAT & PROD.
#      ddl-auto: update
#
#      # To script-based schema creation and data population.
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: never
#      data-locations: classpath:db/schema.sql
#
#logging:
#  level:
#    com.zaxxer.hikari: off # To check the log if the db connection has been established
#



# ====================== Alternative DB ============================
server:
  port: 8080

spring:
  datasource:
    name: borrowmybook_bz9i
    url: jdbc:postgresql://dpg-cgct3sndvk4htnq4hbfg-a.oregon-postgres.render.com/borrowmybook_bz9i
    # TODO: It's not secure to leave credentials in code, need to move to github secrets/vault
    username: borrowmybook_user
    password: hMBChitOx4iFDBDMV9gfP6z69p8NLbTM
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # TODO: using "ddl-auto: none" is good practice. We will use Liquibase/FlyWay for db migration and versioning on UAT & PROD.
      ddl-auto: update

      # To script-based schema creation and data population.
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
      data-locations: classpath:db/schema.sql

logging:
  level:
    com.zaxxer.hikari: off # To check the log if the db connection has been established

# ====================== Alternative DB For Rumi ============================
#server:
#  port: 8080
#
#spring:
#  datasource:
##    name: borrowmybook_bz9i
#    url: jdbc:postgresql://localhost:5432/test
#    # TODO: It's not secure to leave credentials in code, need to move to github secrets/vault
#    username: postgres
#    password: 018687
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect:  org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      # TODO: using "ddl-auto: none" is good practice. We will use Liquibase/FlyWay for db migration and versioning on UAT & PROD.
#      ddl-auto: update
#
#      # To script-based schema creation and data population.
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: never
#      data-locations: classpath:db/schema.sql
#
#logging:
#  level:
#    com.zaxxer.hikari: off # To check the log if the db connection has been established
