server:
  port: 8080

spring:
  datasource:
    name: borrowmybook_bz9i
    url: jdbc:postgresql://dpg-cgct3sndvk4htnq4hbfg-a.oregon-postgres.render.com/borrowmybook_bz9i
    # TODO: It's not secure to leave credentials in code, need to move to github secrets/vault
    username: borrowmybook_user
    password: hMBChitOx4iFDBDMV9gfP6z69p8NLbTM
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # TODO: using "ddl-auto: none" is good practice. We will use Liquibase/FlyWay for db migration and versioning on UAT & PROD.
      ddl-auto: update

      # To script-based schema creation and data population.
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
      data-locations: classpath:db/schema.sql

logging:
  level:
    com.zaxxer.hikari: off # To check the log if the db connection has been established
